---
title: "Pie Server" 
subtitle: "Pi-Hosted"
logo: "logo.png"


header: true 
footer: false
columns: "4"             # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true  # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example)

colors: 
  light: 
    highlight-primary: "#3367d6"  
    highlight-secondary: "#4285f4" 
    highlight-hover: "#5a95f5" 
    background: "#f5f5f5" 
    card-background: "#ffffff" 
    text: "#363636" 
    text-header: "#ffffff" 
    text-title: "#303030" 
    text-subtitle: "#424242" 
    card-shadow: rgba(0, 0, 0, 0.1) 
    link-hover: "#363636"
  dark: 
    highlight-primary: "#3367d6" 
    highlight-secondary: "#4285f4" 
    highlight-hover: "#5a95f5"  
    background: "#131313" 
    card-background: "#2b2b2b" 
    text: "#eaeaea" 
    text-header: "#ffffff" 
    text-title: "#fafafa" 
    text-subtitle: "#f5f5f5" 
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

  

message:
  url: https://api.chucknorris.io/jokes/random
  mapping:
    title: "id"
    content: "value"
  refreshInterval: 10000


  
links: 
  - name: "Contribute" 
    icon: "fab fa-github" 
    url: https://github.com/bastienwirtz/homer 
    target: "_blank" # optional html a tag target attribute
  - name: "HIPHOP NEWS" 
    icon: "fas fa-book" 
    url: https://www.2dopeboyz.com
    target: "_blank" # optional html a tag target attribute
    # Optional navbar

  - name: "Mail"
    icon: "fas fa-envelope"
    url: "https://mail.example.com"

  - name: "Calendar"
    icon: "far fa-calendar"
    url: "https://calendar.example.com"

  - name: "NextCloud"
    icon: "fas fa-cloud"
    url: "https://cloud.example.com"

  - name: "HomeAssistant"
    icon: "fas fa-house-user"
    url: "https://home.example.com"
# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, sect$

 

services:
  - name: "Applications"
    icon: "fas fa-cloud"
    # A path to an image can also be provided. Note that icon take precedence if both icon and logo are set
    items:
      - name: "Reddit"
        logo: "assets/tools/sample.png"
        # Alternatively a fa icon can be provided:
        # icon: "fab fa-jenkins"
        subtitle: "Inspiration"
        tag: "app"
        tagstyle: "is-success"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
      
      - name: "BKtv Channel"
        logo: "assets/tools/sample2.png"
        subtitle: "Visuals"
        tag: "app"
        tagstyle: "is-success"
        url: "https://youtube.com/kudawacho"
        target: "_blank" # optional html a tag target attribute
        # class: "green"
        # background: red
        # target: "_blank"

  - name: "Servers"
    icon: "fa-solid fa-server"
    items:
      - name: "MySQL"
        subtitle: "phpmyadmin"
        icon: "fa-solid fa-server"
        url: "https://192.168.1.64/localhost|phpMyAdmin4.6.6deb5"
        target: "_blank"

      - name: "Radarr"
        subtitle: "movies"
        logo: "assets/white/radarr.png"
        url: "https://radarr.example.com"

      - name: "QBit"
        subtitle: "qbittorrent"
        logo: "assets/white/qbittorrent.png"
        url: "https://qbit.example.com"

      - name: "Plex"
        subtitle: "media server"
        logo: "assets/white/plex.png"
        url: "https://plex.example.com"

      - name: "Deemix"
        subtitle: "music downloader"
        logo: "assets/white/deezer.png"
        url: "http://192.168.1.10:6595"

      - name: "Youtube-DL"
        subtitle: "youtube downloader"
        logo: "assets/white/youtube.png"
        url: "http://192.168.1.10:5000" 

        

